Upgrade to PHPUnit 8.5 (#103)
* Update PHPUnit to 8.5

This is required in order to run tests with Monolog 2. Otherwise this error occurs:

PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

..................PHP Fatal error:  Declaration of Mock_TestHandler_bc3472b7::setFormatter(Monolog\Formatter\FormatterInterface $formatter) must be compatible with Monolog\Handler\AbstractProcessingHandler::setFormatter(Monolog\Formatter\FormatterInterface $formatter): Monolog\Handler\HandlerInterface in /home/danilo/monolog-cascade/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(290) : eval()'d code on line 11

* Fix TestCase inheritance

Fixes this type of error:

`Fatal error: Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found in /home/danilo/monolog-cascade/tests/Config/Loader/FileLoader/FileLoaderAbstractTest.php:26`

* Use TestCase::getMockBuilder instead of TestCase::getMock

Fixes this type of error:

`Error: Call to undefined method Cascade\Tests\Config\Loader\FileLoader\FileLoaderAbstractTest::getMock()`

* Fix HandlerLoaderTest::testHandlerForProcessor

ProcessableHandlerInterface::pushProcessor expects the $callback argument to be a callable. Fixes the following error:

`Cascade\Tests\Config\Loader\ClassLoader\HandlerLoaderTest::testHandlerForProcessor
 TypeError: Argument 1 passed to Mock_TestHandler_aac1a74a::pushProcessor() must be callable, string given, called in /home/danilo/monolog-cascade/src/Config/Loader/ClassLoader/HandlerLoader.php on line 187`

* Remove usages of @expectedException annotations

Fixes this warning:

`The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageMatches() instead.`

Co-authored-by: Danilo Azevedo <danilo.azevedo@datainfo.inf.br>